:nav_mode_func

SET PC, POP


:display_nav

SET PC, POP



; Strings AND Constants
; =======================


:str_Nav1
DAT "Nav Out NW  ", 0
:str_Nav2
DAT "Nav Out WNW ", 0
:str_Nav3
DAT "Nav Out WSW ", 0
:str_Nav4
DAT "Nav OUT SW  ", 0
:str_Nav5
DAT "Nav Out NNW ", 0
:str_Nav6
DAT "NavInner NW ", 0
:str_Nav7
DAT "NavInner SW ", 0
:str_Nav8
DAT "Nav Out SSW ", 0
:str_Nav9
DAT "Nav Out NNE ", 0
:str_Nav10
DAT "NavInner NE ", 0
:str_Nav11
DAT "NavInner SE ", 0
:str_Nav12
DAT "Nav Out SSE ", 0
:str_Nav13
DAT "Nav Out NE  ", 0
:str_Nav14
DAT "Nav Out ENE ", 0
:str_Nav15
DAT "Nav Out ESE ", 0
:str_Nav16
DAT "Nav Out SE  ", 0