:nav_mode_func

SET PC, POP


:display_nav

SET PC, POP



; Strings AND Constants
; =======================


:str_Nav1
DAT "Nav Out A1  ", 0
:str_Nav2
DAT "Nav Out A2  ", 0
:str_Nav3
DAT "Nav Out A3  ", 0
:str_Nav4
DAT "Nav OUT A4  ", 0
:str_Nav5
DAT "Nav Out B1  ", 0
:str_Nav6
DAT "NavInner B2 ", 0
:str_Nav7
DAT "NavInner B3 ", 0
:str_Nav8
DAT "Nav Out B4  ", 0
:str_Nav9
DAT "Nav Out C1  ", 0
:str_Nav10
DAT "NavInner C2 ", 0
:str_Nav11
DAT "NavInner C3 ", 0
:str_Nav12
DAT "Nav Out C4  ", 0
:str_Nav13
DAT "Nav Out D1  ", 0
:str_Nav14
DAT "Nav Out D2  ", 0
:str_Nav15
DAT "Nav Out D3  ", 0
:str_Nav16
DAT "Nav Out D4  ", 0